logging.level:
  org.springframework:
    orm:
      jpa: INFO
      jpa.JpaTransactionManager: DEBUG
    transaction: INFO
    transaction.interceptor: TRACE

spring:
  profiles.active: prod

---
spring:
  config.activate.on-profile: prod
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:schema.sql
  datasource:
    url: jdbc:postgresql://localhost:6432/shareit
    driverClassName: org.postgresql.Driver
    username: shareit
    password: shareit

---
spring:
  config.activate.on-profile: test
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
    show-sql: true
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:schema.sql
  datasource:
    url: jdbc:h2:file:./db/shareit
    driverClassName: org.h2.Driver
    username: shareit
    password: shareit